### ISSUE TITLE
Higher res image in an official product doc would be appreciated

### ISSUE THREAD

**Issue by tomerikko** [NetAppDocs/ontap-sm-classic#21]
Page: [Configure and managing cloud tiers](https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_configuring_managing_cloud_tiers.html)

**Comment by netapp-forry** [comment]
Thanks for letting us know, we'll look into this.

**Comment by netapp-forry** [comment]
We are currently reviewing our graphics standards, and we will plan on making incremental improvements in active content.
Thanks again for your interest in our content.
