### ISSUE TITLE
Link to TR 4597 not working as expected

### ISSUE THREAD

**Issue by jgartrell-missional** [NetAppDocs/ontap-sm-classic#24]
Page: [NFS configuration for ESXi using VSC overview](https://docs.netapp.com/us-en/ontap-sm-classic/nfs-config-esxi/index.html)

Good morning!
 When I click the link at the bottom of the page, trying to access TR 4597 (http://www.netapp.com/us/media/tr-4597.pdf)
why does the link start with http instead of https ?
It redirects me to https://docs.netapp.com/us-en/netapp-solutions/hybrid-cloud/vsphere_ontap_ontap_for_vsphere.html  and that page is not loading for me.  I get a 404 page...

Many thanks!

**Comment by netapp-thomi** [comment]
Hi John,   The links have been fixed now.   Thanks again for alerting us to this problem.   You comments help us keep the documentation accurate and up-to-date.   Thanks,  Thom
