### ISSUE TITLE
Updated docs for OnTap 9.9.x

### ISSUE THREAD

**Issue by jlast159** [NetAppDocs/ontap-sm-classic#35]
Page: [Configure and verify CIFS client access](https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/task_configuring_verifying_client_access.html)

Are there currently or, will there be NetApp docs specifically for 9.9.x being all the docs I've looked at for specific needs are out dated and not accurate for 9.9.x. ?

**Comment by netapp-lenida** [comment]
Hi @jlast159, 
Yes we do have documentation for current ONTAP releases. You should be able to find the updated docs for CIFS/SMB here:
https://docs.netapp.com/us-en/ontap/nas-management/index.html.

**Comment by netapp-forry** [comment]
Two other topics that might be of interest that are comparable to the first topic you cited:
- Provision NAS storage for Windows servers using SMB (using System Manager for ONTAP 9.7 and later)
   https://docs.netapp.com/us-en/ontap/task_nas_provision_windows_smb.html
- Create an SMB share (using the ONTAP CLI)
   https://docs.netapp.com/us-en/ontap/smb-config/create-share-task.html

I hope that helps, please let us know -- thanks.

**Comment by netapp-forry** [comment]
Please let us know if you encounter further issues with our documentation -- thanks again for contacting us.
