### ISSUE TITLE
Clone splitting again

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap-sm-classic#59]
Page: [Split a FlexClone volume from its parent volume with System Manager - ONTAP 9.7 and earlier](https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_splitting_flexclone_volume_from_its_parent_volume.html)

This page is incorrect. Since 9.5, splitting a clone is space-efficient. The split volume does continue to share space with the parent.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Jeffrey -- we'll fix this ASAP.

**Comment by netapp-lenida** [comment]
The topic has been updated to say that the split volume continues to share space with its parent, and that splitting the clone is space efficient.
