### ISSUE TITLE
Typo in Step 4

### ISSUE THREAD

**Issue by ReneMeier** [NetAppDocs/ontap-sm-classic#63]
Page: [Verify LUN reporting nodes after moving a volume](https://docs.netapp.com/us-en/ontap-sm-classic/volume-move/task_verifying_lun_reporting_nodes_after_moving_volume.html)

Wrong syntax at remove-reporting-nodes-remote-nodes:
lun mapping remove-reporting-nodes-remote-nodes -vserver vserver_name -path lun_path -igroup igroup_name

Correct syntax is: 
lun mapping remove-reporting-nodes -remote-nodes true  -vserver vserver_name -path lun_path -igroup igroup_name

Space between remove-reporting-nodes and -remote-nodes | option  -remote-nodes must have true. Same command  shown in 
https://docs.netapp.com/us-en/ontap-sm-classic/volume-move/task_updating_lun_reporting_nodes_after_moving_volume.html

**Comment by netapp-lenida** [comment]
Thanks for letting us know about this, Rene. We'll fix it right away.

**Comment by netapp-lenida** [comment]
This issue should now be fixed. Thanks again, Rene.
