### ISSUE TITLE
generate fr and de - 9254

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/ontap-sm-classic#71]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by netapp-gudugunti** [comment]
Empty fr-fr repository found with language choices deployed on the site.
No de-de repository found.

**Comment by ntap-bmegan** [comment]
German finally turned up.

**Comment by dmajones** [comment]
Sites (fr-fr& de-de) are up and running.
Total TOT: 6 minutes.
