### ISSUE TITLE
Step 2 is wrong

### ISSUE THREAD

**Issue by konstanknetapp** [NetAppDocs/ontap-sm-classic#73]
Page: [Edit SVM settings with System Manager - ONTAP 9.7 and earlier](https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_editing_svm_settings.html)

Tested in ONTAP 9.6
2. Select the SVM, and then click SVM Settings.
Should be changed to 
2. Select the SVM, and then click Edit.

**Comment by netapp-lenida** [comment]
Thanks again, Konstantin. Step 2 has been updated.
