### ISSUE TITLE
Doesnt include references to NLF

### ISSUE THREAD

**Issue by twodotoh** [NetAppDocs/ontap-sm-classic#75]
Page: [Add node-locked licenses](https://docs.netapp.com/us-en/ontap-sm-classic/expansion/task_adding_node_locked_licenses.html)

**Comment by netapp-lenida** [comment]
Thanks @twodotoh. I look into this ASAP.

**Comment by netapp-lenida** [comment]
Updated the topic to include the following information to clarify what versions of ONTAP the topic covers and a pointer to the topic that describes NLFs:

Complete this task if you are using the Classic System Manager UI with ONTAP 9.7 and earlier releases. If you are using the System Manager UI with ONTAP 9.7 and later, see [Enable new features by adding license keys](https://docs.netapp.com/us-en/ontap/task_admin_enable_new_features.html).

For more information about managing licenses, see [Manage licenses overview](https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html).
