### ISSUE TITLE
Incorrect snmp example

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/ontap-sm-classic#78]
### Page URL

https://docs.netapp.com/us-en/ontap-sm-classic/snmp-config/task_testing_snmp_polling.html

### Page title

Test SNMP polling

### Summary

The example here

C:\Windows\System32>snmpwalk -v 3 -a MD5 -l authnopriv -u snmpv3
       -a password123 10.11.12.123 system

should be

C:\Windows\System32>snmpwalk -v 3 -a MD5 -l authnopriv -u snmpv3
       -A password123 10.11.12.123 system

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
The topic has been updated with the corrected example.
