### ISSUE TITLE
nitpick. Page title has a typo

### ISSUE THREAD

**Issue by smorris-ntap** [NetAppDocs/ontap-sm-classic#90]
### Page URL

https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/concept_adding_protocol_volume_to_protocol_enabled_svm.html

### Page title

Add a CIFS volume to a CIFS-enabled SVM

### Summary

https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/concept_adding_protocol_volume_to_protocol_enabled_svm.html

The left hand navigation title starts with "Ad a CIFS..." 
It's a simple typo, should be "Add a CIFS...".

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @smorris-ntap. We'll fix this ASAP.

**Comment by netapp-lenida** [comment]
The typo has been fixed.
